services:
  app:
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-ledgi}:${POSTGRES_PASSWORD:-changeme}@db:5432/${POSTGRES_DB:-ledgi}?schema=public
    depends_on:
      db:
        condition: service_healthy

  migrator:
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-ledgi}:${POSTGRES_PASSWORD:-changeme}@db:5432/${POSTGRES_DB:-ledgi}?schema=public
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: ledgi_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ledgi}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-ledgi}
    volumes:
      - ledgi_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-ledgi} -d ${POSTGRES_DB:-ledgi}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ledgi_pgdata:
